name: Build & Deploy to Public Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "build-and-deploy"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          # Use a Personal Access Token (PAT) for access to the other repo.
          # The GITHUB_TOKEN has permissions only for the current repo.
          token: ${{ secrets.PAT }}

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '23'
          cache: 'npm'

      - name: Update npm to match local version
        run: npm install -g npm@11.4.1

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        timeout-minutes: 5
        run: CI=true npm test -- --verbose=false --silent --reporters=default

      - name: Build static files
        env:
          PUBLIC_URL: https://sportwizard.se
          REACT_APP_SUPABASE_URL: ${{ secrets.REACT_APP_SUPABASE_URL }}
          REACT_APP_SUPABASE_ANON_KEY: ${{ secrets.REACT_APP_SUPABASE_ANON_KEY }}
        run: npm run build

      - name: Push to public repo
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          PERSONAL_TOKEN: ${{ secrets.PAT }}
          external_repository: beggan78/sportwizard
          publish_branch: main
          publish_dir: ./build
          force_orphan: true